name: "Build RebornOS ARM for r58x-4g"
on:
  # push:
  #   branches:
  #     - main
  workflow_dispatch:

jobs:
  build:
    runs-on: [self-hosted, ARM64]
    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        run: |
          sudo pacman -S --noconfirm --needed \
          python python-prettytable python-argparse parted btrfs-progs \
          git wget arch-install-scripts
      - name: Submodule update
        run: git submodule update --init --recursive
      - name: Clean up
        run: |
          sudo rm -rf /tmp/work || true
          sudo rm -rf ./out || true
      - name: Build RebornOS ARM for r58x-4g
        run: |
          sudo python ./mkimage.py -w /tmp/work/ -c ./lxqt-r58x-4g-image/ -o ./out/
          sudo chown -R $USER:$USER ./out/
      - name: Get md5sum, sha256 and sha512 sums
        id: sums
        run: |
          echo "::set-output name=md5sum::$(md5sum ./out/*.img.xz | awk '{print $1}')"
          echo "::set-output name=sha256sum::$(sha256sum ./out/*.img.xz | awk '{print $1}')"
          echo "::set-output name=sha512sum::$(sha512sum ./out/*.img.xz | awk '{print $1}')"
      - name: Get short commit hash
        id: commit
        run: |
          echo "::set-output name=hash::$(git rev-parse --short HEAD)"
      - name: Create release with commit hash
        if: github.event_name == 'workflow_dispatch'
        uses: softprops/action-gh-release@v1
        with:
          repository: RebornOS-Developers/lxqt-r58x-4g-image
          token: ${{ secrets.GH_TOKEN }}
          files: ./out/*.img.xz
          tag_name: ${{ steps.commit.outputs.hash }}
          draft: true
          prerelease: true
          body: |
            md5: ${{ steps.sums.outputs.md5sum }}
            sha256: ${{ steps.sums.outputs.sha256sum }}
            sha512: ${{ steps.sums.outputs.sha512sum }}
          name: RebornOS ARM R58X-4G ${{ steps.commit.outputs.hash }}
        